In [2]:
import pandas as pd
import numpy as np
print('Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers\n','-'*100)
indexdata=pd.date_range('2015-01-01','2015-12-31',freq='B')
df=pd.DataFrame({'Value':np.random.randint(1,100,len(indexdata)).tolist()},index=indexdata)
print('\nTop 5 records from DataFrame\n','-'*30)
print(df.head())
print('\nSum of value of wednesday: ',df[df.index.weekday==2].sum())
print('\nAverage For each calendar month\n','-'*30)
print(df.resample('M').mean())
print('\nFor each group of four consecutive calendar months, find the date on which the highest value occurred \n','-'*100)
df1=df.groupby(pd.Grouper(freq='4M'))
print(df1.idxmax())

print('\nFor validation, printing groups with value:\n','-'*50)
for name,grp in df1:
	print('Group name: ',name)
	print(grp.to_string())

Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers
 ----------------------------------------------------------------------------------------------------

Top 5 records from DataFrame
 ------------------------------
            Value
2015-01-01     31
2015-01-02     89
2015-01-05     38
2015-01-06     80
2015-01-07     97

Sum of value of wednesday:  Value    2921
dtype: int64

Average For each calendar month
 ------------------------------
                Value
2015-01-31  61.227273
2015-02-28  52.700000
2015-03-31  50.863636
2015-04-30  45.045455
2015-05-31  37.952381
2015-06-30  52.772727
2015-07-31  52.043478
2015-08-31  53.428571
2015-09-30  47.227273
2015-10-31  46.454545
2015-11-30  48.238095
2015-12-31  44.652174

For each group of four consecutive calendar months, find the date on which the highest value occurred
 ----------------------------------------------------------------------------------------------------
                Value
2015-01-31 2015-01-07
2015-05-31 2015-03-03
2015-09-30 2015-07-10
2016-01-31 2015-11-06

For validation, printing groups with value:
 --------------------------------------------------
Group name:  2015-01-31 00:00:00
            Value
2015-01-01     31
2015-01-02     89
2015-01-05     38
2015-01-06     80
2015-01-07     97
2015-01-08     12
2015-01-09     62
2015-01-12     81
2015-01-13     69
2015-01-14     97
2015-01-15     49
2015-01-16     66
2015-01-19     58
2015-01-20     95
2015-01-21     95
2015-01-22     15
2015-01-23     47
2015-01-26     49
2015-01-27     28
2015-01-28     82
2015-01-29     67
2015-01-30     40
Group name:  2015-05-31 00:00:00
            Value
2015-02-02     88
2015-02-03     19
2015-02-04     81
2015-02-05      2
2015-02-06      6
2015-02-09     87
2015-02-10     75
2015-02-11     81
2015-02-12     98
2015-02-13     58
2015-02-16     25
2015-02-17     56
2015-02-18     75
2015-02-19     75
2015-02-20     80
2015-02-23     16
2015-02-24     15
2015-02-25     13
2015-02-26     67
2015-02-27     37
2015-03-02     54
2015-03-03     99
2015-03-04      1
2015-03-05     10
2015-03-06     87
2015-03-09     72
2015-03-10     19
2015-03-11     61
2015-03-12     53
2015-03-13     30
2015-03-16     50
2015-03-17     77
2015-03-18     43
2015-03-19     92
2015-03-20     43
2015-03-23     13
2015-03-24     38
2015-03-25     39
2015-03-26     98
2015-03-27     36
2015-03-30     10
2015-03-31     94
2015-04-01     64
2015-04-02     73
2015-04-03     98
2015-04-06     36
2015-04-07     57
2015-04-08     18
2015-04-09     99
2015-04-10     15
2015-04-13     23
2015-04-14     45
2015-04-15      6
2015-04-16     24
2015-04-17     66
2015-04-20     52
2015-04-21      3
2015-04-22     73
2015-04-23     73
2015-04-24      7
2015-04-27     55
2015-04-28     17
2015-04-29     45
2015-04-30     42
2015-05-01     57
2015-05-04     37
2015-05-05      3
2015-05-06     11
2015-05-07     28
2015-05-08     81
2015-05-11     18
2015-05-12     14
2015-05-13     17
2015-05-14     26
2015-05-15      3
2015-05-18     14
2015-05-19     24
2015-05-20     54
2015-05-21      3
2015-05-22     89
2015-05-25     99
2015-05-26     85
2015-05-27     70
2015-05-28     63
2015-05-29      1
Group name:  2015-09-30 00:00:00
            Value
2015-06-01     55
2015-06-02     63
2015-06-03     89
2015-06-04     52
2015-06-05     25
2015-06-08     27
2015-06-09      3
2015-06-10     64
2015-06-11     89
2015-06-12     97
2015-06-15     59
2015-06-16     57
2015-06-17     87
2015-06-18      2
2015-06-19     43
2015-06-22     68
2015-06-23     60
2015-06-24     45
2015-06-25     11
2015-06-26     93
2015-06-29     67
2015-06-30      5
2015-07-01     89
2015-07-02     69
2015-07-03     39
2015-07-06     56
2015-07-07     97
2015-07-08     38
2015-07-09     10
2015-07-10     98
2015-07-13      5
2015-07-14     23
2015-07-15     92
2015-07-16     10
2015-07-17     34
2015-07-20     16
2015-07-21     96
2015-07-22     76
2015-07-23     29
2015-07-24      3
2015-07-27     98
2015-07-28     11
2015-07-29     83
2015-07-30     84
2015-07-31     41
2015-08-03     37
2015-08-04     18
2015-08-05     16
2015-08-06     42
2015-08-07     39
2015-08-10     82
2015-08-11     90
2015-08-12     92
2015-08-13     35
2015-08-14     65
2015-08-17     37
2015-08-18     91
2015-08-19     94
2015-08-20     85
2015-08-21      8
2015-08-24     59
2015-08-25      4
2015-08-26     40
2015-08-27     88
2015-08-28     54
2015-08-31     46
2015-09-01      8
2015-09-02     23
2015-09-03     25
2015-09-04     53
2015-09-07     60
2015-09-08     20
2015-09-09      9
2015-09-10     66
2015-09-11     90
2015-09-14     28
2015-09-15     73
2015-09-16     59
2015-09-17     36
2015-09-18     36
2015-09-21      6
2015-09-22     88
2015-09-23     96
2015-09-24     95
2015-09-25     37
2015-09-28     48
2015-09-29     36
2015-09-30     47
Group name:  2016-01-31 00:00:00
            Value
2015-10-01     72
2015-10-02      5
2015-10-05     65
2015-10-06     39
2015-10-07     97
2015-10-08     80
2015-10-09     12
2015-10-12     63
2015-10-13     64
2015-10-14     94
2015-10-15     26
2015-10-16      8
2015-10-19     21
2015-10-20     64
2015-10-21     97
2015-10-22     41
2015-10-23     37
2015-10-26     84
2015-10-27      6
2015-10-28     38
2015-10-29      1
2015-10-30      8
2015-11-02     13
2015-11-03     87
2015-11-04     21
2015-11-05     30
2015-11-06     99
2015-11-09     55
2015-11-10     42
2015-11-11      7
2015-11-12     63
2015-11-13     98
2015-11-16     69
2015-11-17     68
2015-11-18     43
2015-11-19     54
2015-11-20     19
2015-11-23     89
2015-11-24     39
2015-11-25     44
2015-11-26      4
2015-11-27     15
2015-11-30     54
2015-12-01     95
2015-12-02     34
2015-12-03     87
2015-12-04     15
2015-12-07     27
2015-12-08     23
2015-12-09     39
2015-12-10      9
2015-12-11     14
2015-12-14     21
2015-12-15     89
2015-12-16     74
2015-12-17     21
2015-12-18     27
2015-12-21     97
2015-12-22     65
2015-12-23     45
2015-12-24     68
2015-12-25     29
2015-12-28     52
2015-12-29     49
2015-12-30     26
2015-12-31     21